int get_array_index(char type, int id);
void print_screen(void);
void place_figures(void);
void draw_range(char actor, int xpos, int ypos,int radius, char mode);
void chase_figters(int mnstr, int fightr);
void clear_range();
void clear_screen(void);
void draw_info_panel(void);
void draw_interface(void);
void cleanip(void);
void printip(char txt[20], int line_number);
char analyse_command(char comm[6]);
void clean_side_panel(void);
void print_stats_horisontal(char mode);
void print_to_side_panel(void);
int ask_spells(int pid);
void ascii_battle_init(int current_location, int arena_id);
int player_action_move(int pid);
int player_action_cast(int pid);
int player_action_attack(int pid);
// void move_cursor(int cx, int cy);
int resolve_spell(int pid,char taddr[3],char sid[2]);
int resolve_attack(int pid,char taddr[3]);
int resolve_monster_attack(int mnst,int figh);
int move_fighter(int number_in_array, char letter, int fx, int fy, char target[3]);
int let_move(void);
void monsters_action(void);
int ai_choose_action(int ai_mid);
int dice(int maxv);
void info_screen(void);
int get_fighter_by_position(int x, int y);
void restore_fighters_hp(void);
void cheat_max_hp(void);
int play_battle(int enemy_location, int selected_arena, int mode);
void cheat_max_hp(void);
